spring.application.name=be-u5-w2-d3
# CAMBIO NUMERO PORTA
server.port=3007
# CONFIG DB
spring.datasource.url=jdbc:postgresql://localhost:5432/be-u5-w2-d3
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update